import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="w-full p-4 flex justify-center h-12 gap-2 bg-slate-400">
            <Link href="/dashboard">Dashboard</Link>
            <Link href="login">Login</Link>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  );
}
