import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav className="w-full p-4 flex gap-4 justify-center bg-blue-500/50 mb-4 text-slate-200 font-bold">
            <Link href="/">Home</Link>
            <Link href="/new">Create</Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
